repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
          - id: end-of-file-fixer
          - id: trailing-whitespace

    - repo: https://github.com/igorshubovych/markdownlint-cli
      rev: v0.35.0
      hooks:
          - id: markdownlint-fix

    - repo: https://github.com/python-jsonschema/check-jsonschema
      rev: 0.26.2
      hooks:
        # We don't really have any dependencies here, otherwise...
        #- id: check-dependabot
        - id: check-github-workflows
          verbose: true
          args: ["--verbose"]

        - id: check-github-actions
          verbose: true
          args: ["--verbose"]
