repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: check-yaml

    - repo: https://github.com/igorshubovych/markdownlint-cli
      rev: v0.45.0
      hooks:
          - id: markdownlint

    - repo: https://github.com/python-jsonschema/check-jsonschema
      rev: 0.33.0
      hooks:
        # We don't really have any dependencies here, otherwise...
        - id: check-renovate
          args: ["--verbose"]

        - id: check-github-workflows
          args: ["--verbose"]

        - id: check-github-actions
          args: ["--verbose"]

    - repo: https://github.com/rhysd/actionlint
      rev: v1.7.7
      hooks:
        - id: actionlint
          args: [ -ignore, SC ]

    - repo: https://github.com/crate-ci/typos
      rev: v1.33.1
      hooks:
        - id: typos
