repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
          - id: end-of-file-fixer
          - id: trailing-whitespace

    - repo: https://github.com/igorshubovych/markdownlint-cli
      rev: v0.35.0
      hooks:
          - id: markdownlint-fix
