name: 'PyPI Token Mint'
description: 'Create API token'

inputs:
  audience:
    description: 'audience'
    required: true
    default: 'pypi'

  #request-token:
  #  description: 'request-token'
  #  required: true
    
  #request-url:
  #  description: 'request-url'
  #  required: true
    
outputs:
  api-token:
    description: "api token"
    value: '${{ steps.mint.outputs.api-token }}'

runs:
  using: "composite"
  
  steps:
    - id: mint
      shell: bash
      run: |
        echo  "URL: $ACTIONS_ID_TOKEN_REQUEST_URL"
        
        # This one is not displayed as it is protected...
        echo "TOKEN: $ACTIONS_ID_TOKEN_REQUEST_TOKEN"
          
        resp=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
                       "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=${{ inputs.audience }}")

        # extract the token from the response
        oidc_token=$(jq -r '.value' <<< "${resp}")

        # and move the token into json format
        oidc_token="{\"token\":\"${oidc_token}\"}"

        # use the oidc token to request an api token
        resp=$(curl -X POST https://pypi.org/_/oidc/github/mint-token -d $oidc_token)

        # extract the token from the response
        api_token=$(jq -r '.token' <<< "${resp}")

        echo "api-token=$api_token" >> $GITHUB_OUTPUT
