name: MARKETPLACE

on: push

jobs:
  ci:
    runs-on: ubuntu-latest

    # https://github.com/glassechidna/ghaoidc/issues/1
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v3
     
      - name: Verify environment variables
        run: |
          echo  "URL: $ACTIONS_ID_TOKEN_REQUEST_URL"
          # This one is not displayed as it is protected...
          echo "TOKEN: $ACTIONS_IT_TOKEN_REQUEST_TOKEN"
          
      - name: Mint token
        id: mint
        uses: tschm/token-mint-action@0.0.3
        #with:
        #   audience: pypi

      - name: Check
        run: echo '${{ steps.mint.outputs.api-token }}'
